# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'IosViperArchitectureDemo2' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for IosViperArchitectureDemo2
  pod 'Alamofire', '~> 4.7.3'
  pod 'AlamofireObjectMapper', '~> 5.2'
  pod 'AlamofireImage', '~> 3.3'
  pod 'PKHUD', '~> 5.0'
  pod 'AlamofireNetworkActivityLogger', '~> 2.0'

end
